GET http://localhost:3001/api/persons HTTP/1.1

###
DELETE http://localhost:3001/api/persons/66970ed4b16970fd3707d29b HTTP/1.1
###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "amir mehdian",
    "number": "1143523423"
}

###
GET http://localhost:3001/info HTTP/1.1
